base:
  project: Trash

raw_data:
  data_src: data_source

load_data:
  num_classes: 6
  raw_data: data_source
  preprocessed_data: data/processed
  full_path: data_source

train:
  split_ratio: 0.80

model:
  name: ResNet-18
  trainable: True
  train_path: data/preprocessed/train
  test_path: data/preprocessed/test
  image_size: [255,255]
  loss: categorical 
  batch_size: 32 
  epoch: 5
  sav_dir : models/trained_model.h5

img_augment:
  rescale: 0.0039215686
  vertical_flip: True
  horizontal_flip: True
  shear_range : 0.2
  zoom_range: 0.2
  batch_size: 32 
  The class_mode: 'categorical' 
#  class_mode: categorical in img_augment is used when loading images with ImageDataGenerator in Keras/TensorFlow.
# It tells flow_from_directory() how to format the labels.
# Since trash classification is a multiclass problem, 'categorical' ensures labels are one-hot encoded (e.g., [0,0,1,0,0] for 5 classes).

model_dir : models

mlflow_config:
  artifact_dir: artifacts
  experiment_name: "Deep_LearningResnet-18"
  run_name: learn
  registered_model_name: Seekhing_model
  remote_server_uri: http://127.0.0.1:5000






